`timescale 1ns/1ps
module axi_aes_top (
 input wire S_AXI_ACLK,input wire S_AXI_ARESETN,
 input wire S_AXI_AWID,input wire [5:0] S_AXI_AWADDR,input wire [7:0] S_AXI_AWLEN,
 input wire [2:0] S_AXI_AWSIZE,input wire [1:0] S_AXI_AWBURST,input wire S_AXI_AWVALID,
 output wire S_AXI_AWREADY,input wire [31:0] S_AXI_WDATA,input wire [3:0] S_AXI_WSTRB,
 input wire S_AXI_WLAST,input wire S_AXI_WVALID,output wire S_AXI_WREADY,
 output wire S_AXI_BID,output wire [1:0] S_AXI_BRESP,output wire S_AXI_BVALID,input wire S_AXI_BREADY,
 input wire S_AXI_ARID,input wire [5:0] S_AXI_ARADDR,input wire [7:0] S_AXI_ARLEN,
 input wire [2:0] S_AXI_ARSIZE,input wire [1:0] S_AXI_ARBURST,input wire S_AXI_ARVALID,
 output wire S_AXI_ARREADY,output wire S_AXI_RID,output wire [31:0] S_AXI_RDATA,
 output wire [1:0] S_AXI_RRESP,output wire S_AXI_RLAST,output wire S_AXI_RVALID,input wire S_AXI_RREADY
);
axi_aes_slave u_axi_aes_slave(
 .S_AXI_ACLK(S_AXI_ACLK),.S_AXI_ARESETN(S_AXI_ARESETN),
 .S_AXI_AWID(S_AXI_AWID),.S_AXI_AWADDR(S_AXI_AWADDR),.S_AXI_AWLEN(S_AXI_AWLEN),
 .S_AXI_AWSIZE(S_AXI_AWSIZE),.S_AXI_AWBURST(S_AXI_AWBURST),.S_AXI_AWVALID(S_AXI_AWVALID),.S_AXI_AWREADY(S_AXI_AWREADY),
 .S_AXI_WDATA(S_AXI_WDATA),.S_AXI_WSTRB(S_AXI_WSTRB),.S_AXI_WLAST(S_AXI_WLAST),.S_AXI_WVALID(S_AXI_WVALID),.S_AXI_WREADY(S_AXI_WREADY),
 .S_AXI_BID(S_AXI_BID),.S_AXI_BRESP(S_AXI_BRESP),.S_AXI_BVALID(S_AXI_BVALID),.S_AXI_BREADY(S_AXI_BREADY),
 .S_AXI_ARID(S_AXI_ARID),.S_AXI_ARADDR(S_AXI_ARADDR),.S_AXI_ARLEN(S_AXI_ARLEN),
 .S_AXI_ARSIZE(S_AXI_ARSIZE),.S_AXI_ARBURST(S_AXI_ARBURST),.S_AXI_ARVALID(S_AXI_ARVALID),.S_AXI_ARREADY(S_AXI_ARREADY),
 .S_AXI_RID(S_AXI_RID),.S_AXI_RDATA(S_AXI_RDATA),.S_AXI_RRESP(S_AXI_RRESP),.S_AXI_RLAST(S_AXI_RLAST),.S_AXI_RVALID(S_AXI_RVALID),.S_AXI_RREADY(S_AXI_RREADY)
);
endmodule
